EXE = .exe
INSTALLROOTDIR = /c/opt/EagleSun
INSTALLBINDIR = $(INSTALLROOTDIR)/bin/Win32
ESUNLIBDIR = $(INSTALLROOTDIR)/lib/MinGW
ESUNINCLUDEDIR = $(INSTALLROOTDIR)/include
CC = gcc
CFLAGS = -O3 -I$(ESUNINCLUDEDIR) -I$(ESUNINCLUDEDIR)/ix86_Win32_gcc2
LDFLAGS = -L$(ESUNLIBDIR)
LIBRARIES = $(ESUNLIBDIR)/libesun.a

include Makefile-Common

